# Generated by Django 3.2.1 on 2024-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20)),
                ('moving_date', models.DateField()),
                ('house_size', models.CharField(choices=[('1 Bedroom', '1 Bedroom'), ('2 Bedrooms', '2 Bedrooms'), ('3 Bedrooms', '3 Bedrooms'), ('4+ Bedrooms', '4+ Bedrooms')], max_length=20)),
                ('moving_from', models.CharField(max_length=100)),
                ('moving_to', models.CharField(max_length=100)),
                ('current_house_type', models.CharField(max_length=100)),
                ('destination_house_type', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('extra_services', models.TextField(blank=True)),
                ('more_details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
